# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19cfa2dca8307f87ed0866990f70aded2d3a6ffb72551dfa361609d9c270469e7874265a7feffc12e083a7e2be9e88087286ea242af86ab949d818a0c6b61828

test:
  secret_key_base: f269f308bf24452460713fb4d170209d669315b77bc7ccf83fb7f60f9d5daddf4ca68677aba89a570f0b72989c475b9c506bafac51d2b4e2176176f8c06c598a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
